### ISSUE TITLE
not requiring referenceDate / referenceJulianDate for eras

### ISSUE THREAD

**Issue by eroux** [CalConnect/cc-calendar-systems#10]
While some eras have a clear reference date that people seem to agree on (for instance Kaliyuga starting on February 18th 3102 BCE), in many cases there's no reference date, just a reference year. 

For instance [Vikram Samvat](https://en.wikipedia.org/wiki/Vikram_Samvat) doesn't seem to have such a date, nor do some eras used in Tibet in the 20th c.

Now, if the purpose of the `referenceDate` / `referenceJulianDate` properties is just for calculation, I think any date (even a recent one) can do as the calculation doesn't need to start at 0. If that's the case my proposal would be to change the description of `referenceJulianDate` to be more generic so that eras without a clear beginning date can be encoded in this system.

**Comment by ronaldtse** [comment]
Agree, we should keep this flexible enough.

The purpose of referenceDate/referenceJulianDate was originally only for calculation, we are free to generalise this to accommodate other calendars. 

Would it be possible to help provide a PR to change this? Thanks!

**Comment by eroux** [comment]
sorry to get back to at the last moment before the meeting! I was wanting to create a PR, but I couldn't find the proper files to make a PR against... can you point them to me? thanks!

**Comment by eroux** [comment]
@ronaldtse ?

**Comment by ronaldtse** [comment]
@eroux all the text files are under this section: https://github.com/CalConnect/csd-calendar-systems/tree/master/sources/sections

If you need to change the models, let me know.

**Comment by eroux** [comment]
ok thanks! here's the PR: https://github.com/CalConnect/csd-calendar-systems/pull/13
