### ISSUE TITLE
more properties for day of month and month of year

### ISSUE THREAD

**Issue by eroux** [CalConnect/cc-calendar-systems#11]
First: I don't know if this is in the scope of this work item, I suspect not. If it indeed doesn't, is there anywhere I can report this?

This is a core issue in the design of a solution for non-Gregorian calendars: Asian luni-solar calendars have the notion of leap day of month and month of year.

Typically a sequence of day of the month in such a system is something like `1 2 3 3 4 6` etc., where there are two days numbered 3 and no day numbered 5. In that example, if a date only indicates `3` as day of the month, it's impossible to reconstruct the Julian date as there are two possible matches. The same goes for month of the year, although it happens in more recent calendar systems.

I'm not sure how to best encode that but a proposal could be something along the lines of:
- `X` designates either the first or the only occurrence of day number X in the month
- `Xb` designates the second occurrence of day number X in the month

**Comment by ronaldtse** [comment]
I think we should include this in the document. Can you make a PR to change the doc?

**Comment by eroux** [comment]
well, here's a first attempt: https://github.com/CalConnect/csd-calendar-systems/pull/15 , wdyt?

**Comment by eroux** [comment]
After writing the proposal I was wondering if it might actually be possible to just encode the cardinal value instead of the (more complex) nominal one... but in some cases we don't know the cardinal value (maybe there was a leap month before in the same year in the particular calendar that the date is operating in)...
