### ISSUE TITLE
encoding year cycle and year in year cycle

### ISSUE THREAD

**Issue by eroux** [CalConnect/cc-calendar-systems#9]
There's a phenomenon in Asian calendars where there is a notion of year cycle, and year in year cycle.

For instance in the Tibetan calendar the year cycle is named rabjung (རབ་བྱུང༌།), each rabjung is 60 years. Rabjung number 1 starts in 1027CE. (it's unclear if the previous rabjung is 0 or -1). This year (2020) is in rabjung number 17.

Inside each year cycle each year has a name and/or number. For instance in the Tibetan calendar, this year is named Iron Mouse. Traditionally these years are not referred to by number but since everything is very regular (at least in the Tibetan case), it would be possible to assign each name a number.

Another example of the year cycle / year in cycle use is in South Asian [Samvatsara](https://en.wikipedia.org/wiki/Samvatsara). This system is also used in Tibet although it's less common that the animal / element one. Note that this is a case where some year in cycle can be leaped.

The current model doesn't seem to be really made for that case, but it would seem reasonable to use it in the following way:

Each year cycle could be encoded as an era, and then year in cycle would be the year, so we would have:
- the era *tibrab17* = rabjung number 17
- 2020 is `year = 33, era = tibrab17`

What do you think?

**Comment by ronaldtse** [comment]
@eroux in the Chinese lunar calendar, we are encoding the 60-year cycle and the lunisolar calendar separately as two separate calendars. Would something like this work here, i.e. the Tibetan 60-year cycle as a calendar, and the Tibetan calendar as a separate one?

**Comment by eroux** [comment]
I'm not entirely sure what you mean? I'm still struggling a bit as I haven't seen a real example I could toy with, but basically the 60 years cycle in the Tibetan calendar is the only thing that gives indication about the year, a typical date would be

- day
- month
- year of 60 years cycle (ex: Iron Ox)
- index of 60 years cycle (unfortunately often omitted)

there's no era like in the Chinese calendar

**Comment by ronaldtse** [comment]
@eroux thanks for the clarification. I was confused because the Chinese 60-year cycle does not typically have a specified index, i.e. every cycle is like any other cycle, unless there is a specification of the contemporary era.

I agree that the Tibetan calendar should be encoded as you specified.

**Comment by eroux** [comment]
ok thanks!
